### PR TITLE
Implemented setpoint from stove

### PR DESCRIPTION
**Pull request by mvroosmalen1970**
Added code to get every 10sec the stove temperature setpoint, this also solves incorrect setpoint value in HA after reboot.

### CODE REVIEW

**Comment by aceindy** [comment]
@mvroosmalen Would be very nice if target temp works (been trying to find it on my Qlima, but I doubt it supports it  ;))

**Comment by mvroosmalen1970** [comment]
mmm, what version of evo lod/duepi is in the stove. Mine is 6.89 and
supports. I used wireshark to listen / capture communication

2023-03-15 21:43 GMT+01:00, aceindy ***@***.***>:

**Comment by mvroosmalen1970** [comment]
if state_start & current_state:

is back to original and is incorrect!! please update to the code I
send in earlier push

if state_start & current_state==state_start:


2023-03-15 21:55 GMT+01:00, Mark van Roosmalen ***@***.***>:

**Comment by aceindy** [comment]
@mvroosmalen1970 
We don't need to check if current_state **equals** state_start, but we need to know if current_state **contains**
0x01000000 & current_state (this is a bitwise comparison)
just like the rest:
state_on & current_state
state_eco & current_state
state_cool & current_state
state_off & current_state

**Comment by mvroosmalen** [comment]
??? When you do  &  it results in the mask value when the other contains bitwise the same value. So return is a value not true or false


aceindy   ***@***.*** ***@***.***)>   16 Mar 2023 at 10:56:31   wrote:
>
> @mvroosmalen1970 (https://github.com/mvroosmalen1970)
>   
We don't need to check if current_state  equals  state_start, but we need to know if current_state  contains
>   
0x01000000  &  current_state (this is a bitwise comparison)
>   
just like the rest:
>   
state_on  &  current_state
>   
state_eco  &  current_state
>   
state_cool  &  current_state
>   
state_off  &  current_state

**Comment by mvroosmalen** [comment]
Sorry voor het aandringen, maar probeer dit maar eens in   https://www.w3schools.com/python/trypython.asp?filename=demo_default
mask=0x10000000
 
 
if 0x11001110  &  mask:
   print("OK", 0x11001110  &  mask)
else:
   print("NOK", 0x11001110  &  mask)
 
 
 
 
if 0x01001110  &  mask==mask:
   print("OK", 0x11001110  &  mask)
else:
   print("NOK", 0x11001110  &  mask)
 
dan krijg je dit als output:
OK 268435456
NOK 268435456
Het gaat dus mis bij false!!! de code is echt niet OK in github! kan je ook zien als je naar de log kijkt. je ziet nooit andere status meldingen

Op 2023-03-16 16:29, Mark van Roosmalen  ***@***.***>  schreef:
> ??? When you do  &  it results in the mask value when the other contains bitwise the same value. So return is a value not true or false
>  
>
>
>   
aceindy   ***@***.*** ***@***.***)>   16 Mar 2023 at 10:56:31   wrote:
> >
> > @mvroosmalen1970 (https://github.com/mvroosmalen1970)
> >   
We don't need to check if current_state  equals  state_start, but we need to know if current_state  contains
> >   
0x01000000  &  current_state (this is a bitwise comparison)
> >   
just like the rest:
> >   
state_on  &  current_state
> >   
state_eco  &  current_state
> >   
state_cool  &  current_state
> >   
state_off  &  current_state

**Comment by aceindy** [comment]
Hoe bedoel je geen andere status meldingen ??

Dit is een log van vandaag, iclusief _"Received burner: Ignition starting"_ 

2023-03-16 16:48:54.955 DEBUG (MainThread) [custom_components.duepi_evo.climate] Pellet stove: Received burner: Ignition starting, Ambient temp: 22.0, Fan speed: 1
2023-03-16 16:50:55.283 DEBUG (MainThread) [custom_components.duepi_evo.climate] Pellet stove: Received burner: Flame On, Ambient temp: 22.4, Fan speed: 5
2023-03-16 17:10:55.942 DEBUG (MainThread) [custom_components.duepi_evo.climate] Pellet stove: Received burner: Eco Idle, Ambient temp: 24.1, Fan speed: 0
2023-03-16 19:18:01.255 DEBUG (MainThread) [custom_components.duepi_evo.climate] Pellet stove: Received burner: Cooling down, Ambient temp: 22.7, Fan speed: 0
2023-03-16 19:19:01.249 DEBUG (MainThread) [custom_components.duepi_evo.climate] Pellet stove: Received burner: Off, Ambient temp: 22.6, Fan speed: 0

En aangaande je voorbeeld op W3schools:
als 
_state_start = 0x01000000_
en
_current_state =  0x10111111_
dan geeft
_if state_start  &  current_state:_
exact hetzelfde resultaat als
_if state_start & current_state==state_start:_

Screenshot from 2023-03-16 21-08-12

**Comment by mvroosmalen1970** [comment]
Hoi,

Dit is het probleem:
state_ack = 0x00000020
state_off = 0x00000020
state_start = 0x01000000
state_on = 0x02000000
state_clean = 0x04000000
state_cool = 0x08000000
state_eco = 0x10000000

current_state=0x04010025

if state_start & current_state:
   status = "Ignition starting"
elif state_on & current_state:
   status = "Flame On"
elif state_eco & current_state:
   status = "Eco Idle"
elif state_cool & current_state:
   status = "Cooling down"
elif state_off & current_state:
   status = "Off"
else:
   status = "Error"

print(status)

if state_start & current_state==state_start:
   status = "Ignition starting"
elif state_on & current_state==state_on:
   status = "Flame On"
elif state_clean & current_state==state_clean:
   status = "Clean"
elif state_eco & current_state==state_eco:
   status = "Eco Idle"
elif state_cool & current_state==state_cool:
   status = "Cooling down"
elif current_state==state_off:
   status = "Off"
else:state_ack = 0x00000020
state_off = 0x00000020
state_start = 0x01000000
state_on = 0x02000000
state_clean = 0x04000000
state_cool = 0x08000000
state_eco = 0x10000000

current_state=0x04010025

if state_start & current_state:
   status = "Ignition starting"
elif state_on & current_state:
   status = "Flame On"
elif state_eco & current_state:
   status = "Eco Idle"
elif state_cool & current_state:
   status = "Cooling down"
elif state_off & current_state:
   status = "Off"
else:
   status = "Error"

print(status)

if state_start & current_state==state_start:
   status = "Ignition starting"
elif state_on & current_state==state_on:
   status = "Flame On"
elif state_clean & current_state==state_clean:
   status = "Clean"
elif state_eco & current_state==state_eco:
   status = "Eco Idle"
elif state_cool & current_state==state_cool:
   status = "Cooling down"
elif current_state==state_off:
   status = "Off"
else:
   status = "Error"

print(status)
   status = "Error"

print(state_clean & current_state==state_clean, state_clean &
current_state, status)

onder = OK ==> clean; boven = nok==>off. Waarom bij python een getal
gelijk is aan true was nieuw voor mij. dus je kan mijn code aanhouden
of clean toevoegen ;-)

2023-03-16 21:10 GMT+01:00, aceindy ***@***.***>:

**Comment by aceindy** [comment]
Euh...
Uiteraard kan clean worden toegevoegd, maar het heeft geen functionele waarde (ik heb een vergelijkbaar verzoek voor exhaust gas temperature),
Het probleem is, [de HA climate state](https://developers.home-assistant.io/docs/core/entity/climate/) heeft geen 'clean' mode....

**Comment by mvroosmalen1970** [comment]
Tja zonder die optie krijg je met de huidige code of wat niet juist is. Dat moet error zijnMvg markOn 18 Mar 2023, at 10:40, aceindy ***@***.***> wrote:﻿
Euh...
Uiteraard kan clean worden toegevoegd, maar het heeft geen functionele waarde (ik heb een vergelijkbaar verzoek voor exhaust gas temperature),
Het probleem is, de HA climate state heeft geen 'clean' mode....

**Comment by aceindy** [comment]
> Waarom bij python een getal gelijk is aan true

0 = False, >0 = True

Maar wat ik doe is een bit vergelijking..(bitwise comparison), en die returned True of False

**Comment by mvroosmalen** [comment]
Print eens de output van de bit vergelijk dat is geen true of false

**Pull request merged**
